### ISSUE TITLE
User can search for players

### ISSUE THREAD

**Issue by rocky-truong** [rocky-truong/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for players

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User will see a list of players with the same skill level as their own.
- Each list item will show name of player, NTRP rating, and city.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/58172952/127408919-4e22448b-787e-4ae1-b834-879fafce25b6.png)
![image](https://user-images.githubusercontent.com/58172952/127414851-50ec33f4-f09d-4cce-8c37-60e3254b2d61.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have columns for userId, name, city, ntrp rating. 
- [x] Update `data.sql` to insert "userId, name, city, ntrp rating" into the "users" table for 3 users. 

### ☁️ Server

- [x] Update `index.js` to "get" data from the database.
- [x] Create error messages for 4xx-5xx codes.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a dummy component for the header.jsx and search.jsx to instantly display pages to work with.
- [x] Create index.jsx to render the components from header.jsx and search.jsx.
- [x] Update the component for header.jsx to match the wireframe.
- [x] Update the component for search.jsx to match the wireframe. 

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
