### ISSUE TITLE
User can send a message to another user

### ISSUE THREAD

**Issue by rocky-truong** [rocky-truong/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send a message to another user.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User will be able to click on the search results to initialize a message with that user.
- User will see a blank conversation if they have never messaged that user before.
- User will see the name of the user the are messaging at the top and an input for the message at the bottom.
- After sending a message, the user will see their chat update with their latest message.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/58172952/127536764-fa7db574-191c-481f-857c-3c0c7a7bc516.png)
![image](https://user-images.githubusercontent.com/58172952/127537019-a62ffa9a-73c6-40fa-a73c-56b13961d0b7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have a table for "messages" with columns for two "userId", a unique "messageId", and "message".

### ☁️ Server

- [x] Update `index.js` to "post" data to the database for each message.
- [x] Update `index.js` to check if there is any existing messages when "getting" data from the database.
- [x] Update `index.js` to "get" data from the database for all messages between two users.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `search.jsx` search results to be clickable.
- [x] Create a component for the `chat.jsx`.
- [x] Update component `chat.jsx` to display nothing if new message.
- [x] Update component `chat.jsx` to show input text footer bar.
- [x] Update component `chat.jsx` to show new message after it is sent.
- [x] Update component `chat.jsx` to match the wireframe.

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
